<?php
/**
 * @file
 * taxonomy_and_terms.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function taxonomy_and_terms_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'short hair',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '0040ac21-047d-43b9-acf6-9d5877461357',
    'vocabulary_machine_name' => 'breed',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'baby',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '016a664e-7299-4ef6-a38f-f66afd30b361',
    'vocabulary_machine_name' => 'size',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'pink-eyed white',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '04785676-fb98-439c-9734-271d0f92edf5',
    'vocabulary_machine_name' => 'coat_color',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'crested',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '12ed6d32-8764-4127-8313-ddae7657aa41',
    'vocabulary_machine_name' => 'breed',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'agouti',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 14,
    'uuid' => '1451623e-4d49-410e-9a30-4f8789dc7907',
    'vocabulary_machine_name' => 'coat_color',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Tricolour',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 13,
    'uuid' => '150240ee-5691-479e-ba80-944b84572b20',
    'vocabulary_machine_name' => 'coat_color',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'New Zealand',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 8,
    'uuid' => '17e89956-ae13-4624-8211-8332e0cc02ab',
    'vocabulary_machine_name' => 'breed',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Himalayan - black',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 9,
    'uuid' => '1acfae18-9e23-4ae0-943c-fa0b3b8a239c',
    'vocabulary_machine_name' => 'coat_color',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Himalayan - chocolate',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 10,
    'uuid' => '24f46462-fcaf-47e0-9743-900e0864be2a',
    'vocabulary_machine_name' => 'coat_color',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'white',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '41cf2d85-5acb-426f-8891-b1a15f89908b',
    'vocabulary_machine_name' => 'coat_color',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Peruvian',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '42a774af-e6aa-4cb9-9b8a-815d412da219',
    'vocabulary_machine_name' => 'breed',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'tortoise and white/calico',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 11,
    'uuid' => '44056446-5507-417b-ba2f-660da5f25183',
    'vocabulary_machine_name' => 'coat_color',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'large',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '4a97ecad-2dff-4ab4-87fe-5bee641504e5',
    'vocabulary_machine_name' => 'size',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'gerbil',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5a839cb9-7b9b-4e70-a36e-c0f9ba411077',
    'vocabulary_machine_name' => 'animal_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'teddy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '5c9f9ea2-30f8-473c-89ff-354a538f3d68',
    'vocabulary_machine_name' => 'breed',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'gray',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => '5cd4eb14-9131-4443-bad0-9b5145d68bb9',
    'vocabulary_machine_name' => 'coat_color',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'rat',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5dc8356f-574a-4bd1-b60a-21edd0dc2632',
    'vocabulary_machine_name' => 'animal_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'adoptable',
    'description' => 'Use this to label an animal in our care who is ready to be adopted.',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '698aea96-43f4-44d4-a857-e5719fd9df6e',
    'vocabulary_machine_name' => 'animal_status',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'very large',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '6b4c7a32-9c88-4c76-a4a5-51ad0ad1b44e',
    'vocabulary_machine_name' => 'size',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'beige',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '6c47f4de-54f4-47cd-b1fc-578cc2aa8549',
    'vocabulary_machine_name' => 'coat_color',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'very small',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '70d08bbc-0913-4fcf-82d0-8dbbff576563',
    'vocabulary_machine_name' => 'size',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'hamster',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '875dd9ba-9ea6-4d79-b1d7-44b053b7ff6f',
    'vocabulary_machine_name' => 'animal_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Tortoiseshell',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 12,
    'uuid' => '8b190165-2c59-4499-a13b-15bf980dc8eb',
    'vocabulary_machine_name' => 'coat_color',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'black',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => '98fe2af2-c845-4358-8602-ac82318edafe',
    'vocabulary_machine_name' => 'coat_color',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'mouse',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9b71a437-713d-48d6-b9f6-55a6c64760d9',
    'vocabulary_machine_name' => 'animal_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'black and white',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 8,
    'uuid' => 'a700bc56-c1ef-4b0d-9e5c-b48112a240f6',
    'vocabulary_machine_name' => 'coat_color',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'mini lop',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => 'ae873baf-c0c1-4c07-92dd-394f71c42329',
    'vocabulary_machine_name' => 'breed',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Abyssinian',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'aec9fedd-e4ad-4cda-a933-a407ab88128f',
    'vocabulary_machine_name' => 'breed',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'rabbit',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b060962d-92f6-4ca0-b4bb-a59f6812b37f',
    'vocabulary_machine_name' => 'animal_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'foster care',
    'description' => 'Use this to label an animal who is in foster care but not yet ready to be adopted. ',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b4d939a1-5119-4697-9c60-aa6ddb3522ef',
    'vocabulary_machine_name' => 'animal_status',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'brown',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => 'b842f790-83c2-4df1-bc4e-7ee267c81273',
    'vocabulary_machine_name' => 'coat_color',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'guinea pig',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'bf3f2d6e-4b21-487d-beca-d627e97c1a04',
    'vocabulary_machine_name' => 'animal_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'cream',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'c948e89f-137d-44d8-927f-8bb0b8080e79',
    'vocabulary_machine_name' => 'coat_color',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'small',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'd87916b9-f681-434b-9c25-5886359ce29f',
    'vocabulary_machine_name' => 'size',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'adopted',
    'description' => 'Use this to label an animal who has been adopted so that we can track success stories!',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'db0f0902-c22a-4534-8c2a-032f90b0c48f',
    'vocabulary_machine_name' => 'animal_status',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'tan',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'e3458db6-0a99-46a9-a2fd-36c81f4b7de9',
    'vocabulary_machine_name' => 'coat_color',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'dwarf',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => 'e516b423-2fbf-4f0d-a76c-5fc4dcd32a35',
    'vocabulary_machine_name' => 'breed',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'skinny',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => 'e9d054f0-7558-4e67-8a2d-5ddf909da209',
    'vocabulary_machine_name' => 'breed',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'to be surrendered',
    'description' => 'Use this to label to put an animal in the system who is to be surrendered but not yet in our care.',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f5429f94-a456-4cf9-9f84-3267851f6318',
    'vocabulary_machine_name' => 'animal_status',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'medium',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'fb5f97df-8d24-4af4-9523-3dae44b643c9',
    'vocabulary_machine_name' => 'size',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  return $terms;
}
